// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PC3prog.Models;

namespace PC3prog.Migrations
{
    [DbContext(typeof(PublicacionContext))]
    [Migration("20210525225242_publicacion")]
    partial class publicacion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CategoriaPublicacion", b =>
                {
                    b.Property<int>("PublicacionesId")
                        .HasColumnType("integer");

                    b.Property<int>("categoriasId")
                        .HasColumnType("integer");

                    b.HasKey("PublicacionesId", "categoriasId");

                    b.HasIndex("categoriasId");

                    b.ToTable("CategoriaPublicacion");
                });

            modelBuilder.Entity("PC3prog.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PC3prog.Models.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DescripcionPubli")
                        .HasColumnType("text");

                    b.Property<string>("Foto")
                        .HasColumnType("text");

                    b.Property<string>("LugarCompra")
                        .HasColumnType("text");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("CategoriaPublicacion", b =>
                {
                    b.HasOne("PC3prog.Models.Publicacion", null)
                        .WithMany()
                        .HasForeignKey("PublicacionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PC3prog.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("categoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
